version: "3.8"

services:
  php:
    image: php:8.2-fpm
    container_name: php_container_teste
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql_container_teste
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha_root
      MYSQL_DATABASE: seu_banco_de_dados
      MYSQL_USER: seu_usuario
      MYSQL_PASSWORD: sua_senha
    ports:
      - "3307:3307"
    volumes:
      - ./dados_mysql:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container_teste
    links:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: seu_usuario
      PMA_PASSWORD: sua_senha
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
